[meta]
  title = "Live Transcription Flask Starter"
  description = "Basic demo for using Deepgram to transcribe microphone audio in Flask"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Live"
  language = "Python"
  framework = "Flask"

[build]
  command = "pip install -r requirements.txt"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "Run `python app.py` to get up and running." # message to give users once setup is complete
